

DROP TABLE IF EXISTS EMPLOYEES;
CREATE TABLE EMPLOYEES
(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    IDENTIFICATION VARCHAR(30) NOT NULL,
    SALARY INTEGER(100),
    CONTRACTTYPE VARCHAR(60) NOT NULL,
    CONTRACTSTARDATE VARCHAR(60) NOT NULL,
    POSITION VARCHAR(100) NOT NULL
)